{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-phosphoricons
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/phosphoricons_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/phosphoricons/phosphoricons_{{ version }}.tar.gz
  sha256: c3904dc35db6cdbeb24a29b1fe44bced2cbcebf474ff9c651de7c46ffbc3383d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools >=0.3
  run:
    - r-base
    - r-htmltools >=0.3

test:
  commands:
    - $R -e "library('phosphoricons')"           # [not win]
    - "\"%R%\" -e \"library('phosphoricons')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=phosphoricons
  license: MIT
  summary: Use 'Phosphor' icons in 'shiny' applications or 'rmarkdown' documents. Icons are available in 5 different weights and can be customized by setting color, size, orientation and more.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
